### PR TITLE
Better zooming & panning

### PR DESCRIPTION
**Pull request by adeas31**
Removed zoom & pan buttons.
Zoom is default.
Panning is done by pressing the control key.

### CODE REVIEW

**Comment by adeas31** [comment]
@lochel is this PR helpful?

**Comment by lochel** [comment]
@adeas31 Sounds very good – thanks!

**Comment by hkiel** [comment]
@lochel @adeas31 Would a double-click be appropriate for "fit in view"?

**Comment by hkiel** [comment]
@adeas31 Can we make OMPlot localized? The relevant strings are marked with tr(), but there is no QTranslator object.

**Comment by lochel** [comment]
@hkiel wrote:
> Would a double-click be appropriate for "fit in view"?

Sounds fine for me.

Btw, what can I do with the "Auto Scale" button?

**Comment by adeas31** [comment]
You can already do "fit in view" through control + right click.

**Comment by adeas31** [comment]
Yes we could localize OMPlot. Wouldn't be too hard since translations are already there as part of `OMEdit`.

**Comment by adeas31** [comment]
@lochel if `Auto Scale` is not checked then plotting a new curve will not call "fit in view".

**Pull request merged**
