### PR TITLE
Support for interactive plot windows

### PR DESCRIPTION
**Pull request by chrjo5**

### CODE REVIEW

**Comment by adeas31** [comment]
Can you squash your commits?

**Comment by chrjo5** [comment]
Sure, I'll close this one and make another request with squashed commits.

**Comment by sjoelund** [comment]
You can change the branch of the PR and push --force in order to not create new PRs 

⁣Sent from BlueMail ​

**Comment by chrjo5** [comment]
Okay that's good to know. Unfortunately I didn't notice your comment until the other one was created...

**Pull request closed without merging**
